name: Merge

on:
  schedule:
    - cron: "0 0 * * 6"

jobs:
  Merge:
    runs-on: ubuntu-latest
    if: github.repository != 'NebulaSS13/Nebula'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 25
      - name: Fetching
        run: |
          git remote add upstream https://github.com/NebulaSS13/Nebula
          git fetch --all
      - name: Merge
        run: |
          git merge upstream/dev
          git config --local user.email "action@github.com"
          git config --local user.name "Upstream Merger"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev

